# Generated by Django 2.0.8 on 2018-09-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descrição', models.TextField()),
                ('estoque', models.TextField(verbose_name=int)),
            ],
        ),
    ]
