# Generated by Django 2.0.8 on 2018-09-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descrição',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.CharField(max_length=60, verbose_name=int),
        ),
    ]
