# Generated by Django 2.0.8 on 2018-09-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_auto_20180913_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.CharField(max_length=60, verbose_name=0),
        ),
    ]
