# Generated by Django 2.0.8 on 2018-09-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_auto_20180913_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='descrição',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='titulo',
            new_name='nome_do_produto',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='estoque',
        ),
    ]
