# Generated by Django 2.0.8 on 2018-09-13 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_auto_20180913_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='nome_do_produto',
            new_name='nome',
        ),
    ]
