# Generated by Django 2.0.8 on 2018-09-13 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_auto_20180913_1649'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estoque',
        ),
    ]
