# Generated by Django 2.0.8 on 2018-09-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_delete_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cor',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
        migrations.AddField(
            model_name='produto',
            name='tamanho',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(max_length=400),
        ),
    ]
